import { expect, test } from '@playwright/test'

test('completes the local fixture checkout without Supabase', async ({ page }) => {
  test.skip(Boolean(process.env.E2E_BASE_URL), 'local fixture checkout only')

  await page.goto('/login')
  await page.getByLabel('Email 或手機號碼').fill('admin@mori.tw')
  await page.getByLabel('密碼', { exact: true }).fill('mori123456')
  await page.getByRole('button', { name: '登入' }).click()
  await expect(page).toHaveURL('/admin')
  await page.goto('/products/mori-organic-cotton-tee')
  await page.getByRole('button', { name: '尺寸 100' }).click()
  await page.getByRole('button', { name: '加入購物車' }).click()
  await page.goto('/checkout')
  await expect(page.getByLabel('結帳進度').locator('li', { hasText: '填寫資料' })).toHaveAttribute('aria-current', 'step')

  await page.getByRole('radio', { name: '全家', exact: true }).check()
  await expect(page.getByRole('radio', { name: '全家', exact: true })).toBeChecked()
  await expect(page.getByRole('button', { name: '開啟全家門市地圖' })).toBeVisible()
  await page.getByRole('radio', { name: '7-ELEVEN', exact: true }).check()

  await page.getByLabel('Email', { exact: true }).fill('preview-parent@example.com')
  await page.getByLabel('收件人姓名').fill('王小美')
  await page.getByLabel('手機號碼').fill('0912345678')
  await page.getByLabel('取貨門市名稱').fill('台北門市')
  await page.getByLabel('門市店號').fill('123456')
  await page.getByLabel('訂單留言（選填）').fill('請協助確認包裝完整，謝謝。')
  await page.getByRole('button', { name: '送出資料，確認訂單' }).click()

  await expect(page).toHaveURL(/\/checkout\/payment\/[0-9a-f-]+$/)
  await expect(page.getByRole('heading', { name: '訂單確認' })).toBeVisible()
  await expect(page.getByLabel('結帳進度').locator('li', { hasText: '訂單確認' })).toHaveAttribute('aria-current', 'step')
  await expect(page.getByRole('img', { name: '有機棉小樹 T 恤' })).toBeVisible()
  await expect(page.getByText('MORI-E2E-SAGE-100')).toBeVisible()
  await expect(page.getByText('台北門市', { exact: true })).toBeVisible()
  await expect(page.getByText('銀行匯款', { exact: true })).toBeVisible()
  await expect(page.getByText('preview-parent@example.com')).toBeVisible()
  await expect(page.getByText('請協助確認包裝完整，謝謝。')).toBeVisible()

  await page.getByRole('link', { name: '返回修改資料', exact: true }).click()
  await expect(page).toHaveURL('/checkout')
  await expect(page.getByLabel('Email', { exact: true })).toHaveValue('preview-parent@example.com')
  await expect(page.getByLabel('收件人姓名')).toHaveValue('王小美')
  await expect(page.getByLabel('取貨門市名稱')).toHaveValue('台北門市')
  await expect(page.getByLabel('門市店號')).toHaveValue('123456')
  await expect(page.getByLabel('訂單留言（選填）')).toHaveValue('請協助確認包裝完整，謝謝。')
  await page.getByRole('button', { name: '送出資料，確認訂單' }).click()
  await expect(page).toHaveURL(/\/checkout\/payment\/[0-9a-f-]+$/)

  await page.getByRole('button', { name: '確認資料並送出訂單' }).click()
  await page.getByRole('checkbox', { name: /我已確認/ }).check()
  await page.getByRole('button', { name: '確認送出訂單' }).click()

  await expect(page).toHaveURL(/\/order-complete\/MORI-DEMO-/)
  await expect(page.getByRole('heading', { name: '訂單完成' })).toBeVisible()
  await expect(page.getByRole('heading', { name: '匯款資訊' })).toBeVisible()
  await page.getByLabel('帳號末 5 碼').fill('98765')
  await page.getByRole('button', { name: '送出末 5 碼' }).click()
  await expect(page.getByRole('status')).toContainText('末 5 碼已送出')
  await expect(page.getByRole('heading', { name: '接下來的配送進度' })).toBeVisible()
  await expect(page.getByRole('link', { name: '前往我的訂單' })).toBeVisible()
  const orderNumber = new URL(page.url()).pathname.split('/').at(-1)!
  await expect.poll(() => page.evaluate(() => window.localStorage.getItem('mori-cart-v1')))
    .toBe('[]')

  await page.goto('/order-lookup')
  await page.getByLabel('訂單編號').fill(orderNumber)
  await page.getByLabel('Email', { exact: true }).fill('preview-parent@example.com')
  await page.getByRole('button', { name: '查詢訂單' }).click()

  await expect(page.getByText(orderNumber)).toBeVisible()
  await expect(page.getByText('王小美（0912345678）')).toBeVisible()
  await expect(page.getByLabel('帳號末 5 碼')).toHaveValue('98765')

  await page.goto('/products/mori-organic-cotton-tee')
  await page.getByRole('button', { name: '尺寸 100' }).click()
  await page.getByRole('button', { name: '加入購物車' }).click()
  await page.goto('/checkout')
  await expect(page.getByLabel('Email', { exact: true })).toHaveValue('preview-parent@example.com')
  await expect(page.getByLabel('收件人姓名')).toHaveValue('王小美')
  await expect(page.getByLabel('手機號碼')).toHaveValue('0912345678')
  await expect(page.getByRole('radio', { name: '7-ELEVEN', exact: true })).toBeChecked()
  await expect(page.getByLabel('取貨門市名稱')).toHaveValue('台北門市')
  await expect(page.getByLabel('門市店號')).toHaveValue('123456')
})
